version: "3"
services:
       login-app:
           container_name: sells
           image: sells
           restart: always
           build: .
           ports:
             - "3000:8080"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27018:27017'